version: '3.9'

services: 
    db:
        image: mysql:5.7
        volumes: 
            # este volumen sera accesible solo a este servicio
            - db_data:/var/lib/mysql
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
    
    wordpress:
        # La imagen de wordpress no se levantará hasta que la BBDD se halla levantado
        depends_on: 
            - db
        image: wordpress:latest
        ports: 
            - "8000:80"
        restart: always
        environment: 
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
volumes: 
    # estos volumenes serna accesibles a todos los servicios
    db_data: {}