#FROM is the base image for which we will run our application
FROM nginx:latest
# Copy files and directories from the application
ADD html/ /usr/share/nginx/html

# Tell Docker we are going to use this port
EXPOSE 80